# PANDAS

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.Series([1,2,3,4,5])

In [4]:
data

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [9]:
data[:5:2]

0    1
2    3
4    5
dtype: int64

In [10]:
type(data)

pandas.core.series.Series

In [2]:
data1 = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
data1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [3]:
p = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(p)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [4]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [16]:
states = pd.DataFrame({'Area' : area , 'Population' : p})
states

Area  Population
California  423967    38332521
Texas       695662    26448193
New York    141297    19651127
Florida     170312    19552860
Illinois    149995    12882135

In [21]:
states.index


Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [22]:
states.columns

Index(['Area', 'Population'], dtype='object')

In [63]:
states[['Population']]

Population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [65]:
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [73]:
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [79]:
pd.DataFrame([{'a': 1, 'b': 2}, { 'c': 4,'d' : 7}])

a    b    c    d
0  1.0  2.0  NaN  NaN
1  NaN  NaN  4.0  7.0

In [71]:
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

foo       bar
a  0.035229  0.428693
b  0.918790  0.629485
c  0.933156  0.230586

In [88]:
A = np.zeros(3,dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [89]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

In [90]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [91]:
indA[::2]

Int64Index([1, 5, 9], dtype='int64')

In [92]:
print(indA.size, indA.shape, indA.ndim, indA.dtype)

5 (5,) 1 int64


In [93]:
indA & indB  # intersection

<ipython-input-93-4d2a3e5acbb8>:1: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead
  indA & indB  # intersection


Int64Index([3, 5, 7], dtype='int64')

In [95]:
indA.intersection(indB)

Int64Index([3, 5, 7], dtype='int64')

In [96]:
indA.union(indB)

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [97]:
indA.difference(indB)

Int64Index([1, 9], dtype='int64')

In [99]:
list(p.items())

[('California', 38332521),
 ('Texas', 26448193),
 ('New York', 19651127),
 ('Florida', 19552860),
 ('Illinois', 12882135)]

In [104]:
p['Los Angles'] = 123456
p

{'California': 38332521,
 'Texas': 26448193,
 'New York': 19651127,
 'Florida': 19552860,
 'Illinois': 12882135,
 'Los Angles': 123456}

In [105]:
p['Texas'] = 123
p

{'California': 38332521,
 'Texas': 123,
 'New York': 19651127,
 'Florida': 19552860,
 'Illinois': 12882135,
 'Los Angles': 123456}

In [106]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [116]:
data['a' : 'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [119]:
data[0:4:3]

a    0.25
d    1.00
dtype: float64

In [120]:
data[['a','d']]

a    0.25
d    1.00
dtype: float64

In [142]:
data[(data > .4) & (data <=1)]

b    0.50
c    0.75
d    1.00
dtype: float64

In [143]:
d = pd.Series(['a', 'b', 'c','d','e','f','g'], index=[1, 2, 3,4,5,6,7])
d

1    a
2    b
3    c
4    d
5    e
6    f
7    g
dtype: object

In [146]:
d.loc[2]

'b'

In [147]:
d.iloc[2]

'c'

In [149]:
d.loc[3:5]

3    c
4    d
5    e
dtype: object

In [150]:
d.iloc[3:5]

4    d
5    e
dtype: object

In [26]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [27]:
data.loc[ :'Florida', :'area']

area
California  423967
Texas       695662
New York    141297
Florida     170312

In [35]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [29]:
data.ix[:2,:'density']

AttributeError: 'DataFrame' object has no attribute 'ix'

In [30]:
data.ix[:3, :'pop']

AttributeError: 'DataFrame' object has no attribute 'ix'

In [37]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [36]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [45]:
data.loc[data.density > 100,['pop']]

pop
New York  19651127
Florida   19552860

In [46]:
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

In [48]:
data.loc['Texas','density']=0
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193    0.000000
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [49]:
data.iloc[0,2]=0
data

area       pop     density
California  423967  38332521    0.000000
Texas       695662  26448193    0.000000
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [104]:
rng = np.random.RandomState(42)
ser = pd.Series(np.random.randint(0, 10, 4))
ser

0    4
1    2
2    6
3    0
dtype: int64

In [105]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  3  7  4
1  6  9  2  6
2  7  4  3  7

In [106]:
np.exp(ser)

0     54.598150
1      7.389056
2    403.428793
3      1.000000
dtype: float64

In [107]:
np.sin((df * np.pi)/4) 

A             B         C             D
0 -1.000000  7.071068e-01 -0.707107  1.224647e-16
1 -1.000000  7.071068e-01  1.000000 -1.000000e+00
2 -0.707107  1.224647e-16  0.707107 -7.071068e-01

In [108]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967})
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127})


In [111]:
 population / area 

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [114]:
area.index & population.index

<ipython-input-114-b9ff7eadeba7>:1: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead
  area.index & population.index


Index(['Texas', 'California'], dtype='object')

In [121]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))
A


A  B
0   2  1
1  11  5

In [128]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
B

B  A  C
0  6  3  8
1  2  4  2
2  6  4  8

In [138]:
fill = A.stack().mean()
A.mul(B,fill_value=fill)

A     B     C
0   6.0   6.0  38.0
1  44.0  10.0   9.5
2  19.0  28.5  38.0

In [149]:
a=np.random.randint(0,20,size = (5,5))
a

array([[16,  8, 16, 18, 12],
       [10,  4,  8,  0, 13],
       [12, 16, 19,  5, 13],
       [14,  6, 10,  7, 17],
       [ 4, 19,  6, 19,  5]])

In [150]:
a-a[0]

array([[  0,   0,   0,   0,   0],
       [ -6,  -4,  -8, -18,   1],
       [ -4,   8,   3, -13,   1],
       [ -2,  -2,  -6, -11,   5],
       [-12,  11, -10,   1,  -7]])

In [152]:
pa=pd.DataFrame(a,columns=list('abcde'))
pa

a   b   c   d   e
0  16   8  16  18  12
1  10   4   8   0  13
2  12  16  19   5  13
3  14   6  10   7  17
4   4  19   6  19   5

#### rowwise subtraction

In [167]:
pa - pa.iloc[0]

a   b   c   d  e
0   0   0   0   0  0
1  -6  -4  -8 -18  1
2  -4   8   3 -13  1
3  -2  -2  -6 -11  5
4 -12  11 -10   1 -7

#### Columnwise subtraction

In [177]:
pa.sub(pa['d'],axis=0)

a   b   c  d   e
0  -2 -10  -2  0  -6
1  10   4   8  0  13
2   7  11  14  0   8
3   7  -1   3  0  10
4 -15   0 -13  0 -14

In [189]:
df

A  B  C  D
0  6  3  7  4
1  6  9  2  6
2  7  4  3  7

In [194]:
halfrow = df.iloc[0:, ::2]
halfrow

A  C
0  6  7
1  6  2
2  7  3

## Handling Missing Data

### NONE AND NAN IN NUMPY

#### None - A Python Object

In [2]:
vals1 = np.array([1, None, 3, 4])
vals1


array([1, None, 3, 4], dtype=object)

In [3]:
vals1.min()

TypeError: '<=' not supported between instances of 'int' and 'NoneType'

#### NAN (Not A Number) - It is a special Floating-Point Value

In [4]:
vals2 = np.array([1, np.nan, 3, 4]) 
vals2

array([ 1., nan,  3.,  4.])

In [5]:
vals2.dtype

dtype('float64')

In [12]:
vals2.sum(),vals2.min(),vals2.max()


(nan, nan, nan)

#### Numpy Functions to omit NAN values 

In [11]:
np.nansum(vals2),np.nanmin(vals2),np.nanmean(vals2)

(8.0, 1.0, 2.6666666666666665)

 - Keep in mind that NaN is specifically a floating-point value; there is no equivalent NaN value for integers, strings, or other types.

### NONE AND NAN IN PANDAS

In [13]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [14]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int64

In [15]:
x[0]=None
x

0    NaN
1    1.0
dtype: float64

#### Typeclass	Conversion When Storing NAs	NA Sentinel Value
- floating	No change	np.nan
- object	No change	None or np.nan
- integer	Cast to float64	np.nan
- boolean	Cast to object	None or np.nan


- isnull(): Generate a boolean mask indicating missing values
- notnull(): Opposite of isnull()
- dropna(): Return a filtered version of the data
- fillna(): Return a copy of the data with missing values filled or imputed

## Handling the null values 

#### SERIES ( Checking for null and droping the null values)

In [42]:
data=pd.Series([1,2,np.nan,5,None,6])
data

0    1.0
1    2.0
2    NaN
3    5.0
4    NaN
5    6.0
dtype: float64

In [43]:
data.isnull()

0    False
1    False
2     True
3    False
4     True
5    False
dtype: bool

In [44]:
data.notnull()

0     True
1     True
2    False
3     True
4    False
5     True
dtype: bool

In [45]:
data.dropna()


0    1.0
1    2.0
3    5.0
5    6.0
dtype: float64

#### DATAFRAME (Checking for null and droping the null values)

In [110]:
t=pd.DataFrame([[1,2,3,np.nan],
              [5,6,7,8],
              [9,10,np.nan,11],
              [12,13,np.nan,None]])
t

0   1    2     3
0   1   2  3.0   NaN
1   5   6  7.0   8.0
2   9  10  NaN  11.0
3  12  13  NaN   NaN

In [47]:
t.isnull()

0      1      2      3
0  False  False  False   True
1  False  False  False  False
2  False  False   True  False
3  False  False   True   True

In [48]:
t.notnull()

0     1      2      3
0  True  True   True  False
1  True  True   True   True
2  True  True  False   True
3  True  True  False  False

In [49]:
t.dropna()

0  1    2    3
1  5  6  7.0  8.0

In [50]:
t.dropna(axis=1)

0   1
0   1   2
1   5   6
2   9  10
3  12  13

In [51]:
t.dropna(axis=0)

0  1    2    3
1  5  6  7.0  8.0

In [111]:
t[3]=np.nan
t

0   1    2   3
0   1   2  3.0 NaN
1   5   6  7.0 NaN
2   9  10  NaN NaN
3  12  13  NaN NaN

In [53]:
t.dropna(axis=1,how='any')

0   1
0   1   2
1   5   6
2   9  10
3  12  13

In [54]:
t.dropna(axis=1,how='all')

0   1    2
0   1   2  3.0
1   5   6  7.0
2   9  10  NaN
3  12  13  NaN

#### SERIES (Filling the null values)

In [55]:
data

0    1.0
1    2.0
2    NaN
3    5.0
4    NaN
5    6.0
dtype: float64

In [56]:
data.fillna(0)

0    1.0
1    2.0
2    0.0
3    5.0
4    0.0
5    6.0
dtype: float64

In [57]:
data.fillna(method='ffill')

0    1.0
1    2.0
2    2.0
3    5.0
4    5.0
5    6.0
dtype: float64

In [58]:
data.fillna(method='bfill')

0    1.0
1    2.0
2    5.0
3    5.0
4    6.0
5    6.0
dtype: float64

#### DATAFRAME(Filling the null values)

In [112]:
t

0   1    2   3
0   1   2  3.0 NaN
1   5   6  7.0 NaN
2   9  10  NaN NaN
3  12  13  NaN NaN

In [61]:
t.fillna(0)

0   1    2    3
0   1   2  3.0  0.0
1   5   6  7.0  0.0
2   9  10  0.0  0.0
3  12  13  0.0  0.0

In [66]:
t.fillna(method='ffill',axis=1)

0     1     2     3
0   1.0   2.0   3.0   3.0
1   5.0   6.0   7.0   7.0
2   9.0  10.0  10.0  10.0
3  12.0  13.0  13.0  13.0

In [115]:
t.fillna(t[2].mean(),axis=0)

0   1    2    3
0   1   2  3.0  5.0
1   5   6  7.0  5.0
2   9  10  5.0  5.0
3  12  13  5.0  5.0

In [107]:
t.drop([3], axis = 1, inplace = True)
t

0   1    2
0   1   2  3.0
1   5   6  7.0
2   9  10  NaN
3  12  13  NaN